# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b92ac057e4839cc171c3f10576a77790d7c6004cefcce71041e95964bfc5ad9fb374eb6f8f591f3c8e55cedda10ddba81f5eb32ff1170bea83da3ab1abfb4d

test:
  secret_key_base: 3cd9d3ed10f065a5848e5e5a7ab66a4a4b8d59d28e7117b9e5c3c5f5f133d09033fc66a2505ddb2c02f1a5f6cf36b2debc3f24a198b3792951224f6751aa9057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
